import React, { useState } from "react";
import { Grid, Paper } from "@mui/material";
import Head from "next/head";

import AutoGeneratedFieldGroup from "components/AutoGeneratedFieldGroup";
import * as data from "data.json";

export default function Home() {
  const [input, setInput] = useState(data.data);
  const [output, setOutput] = useState([]);

  return (
    <Grid container justifyContent={"center"}>
      <Head>
        <title>Auto Generated Field Group Example</title>
        <meta
          name="description"
          content="Small example to demonstrate the Auto Generated Field Group component."
        />
      </Head>
      <Grid item xs={8} sx={{ mb: 3 }}>
        <h1>AutoGeneratedFieldGroup example</h1>
      </Grid>
      <Grid item xs={8} sx={{ mb: 5 }}>
        <Paper elevation={3} rounded sx={{ p: 5 }}>
          <h3> Input data:</h3>
          <Grid item>
            <PrettyPrintJson data={input} />
          </Grid>
        </Paper>
      </Grid>
      <Grid item xs={8} sx={{ mb: 5 }}>
        <Paper elevation={3} rounded sx={{ p: 5 }}>
          <Grid item>
            <h3> Generated fields:</h3>
            <AutoGeneratedFieldGroup data={input} onChange={setOutput} />
          </Grid>
        </Paper>
      </Grid>
      <Grid item xs={8}>
        <Paper elevation={3} rounded sx={{ p: 5 }}>
          <h3> Output data:</h3>
          <PrettyPrintJson data={output} />
        </Paper>
      </Grid>
    </Grid>
  );
}

const PrettyPrintJson = ({ data }) => (
  <div>
    <pre>{JSON.stringify(data, null, 2)}</pre>
  </div>
);
